# Generated by Django 3.1.1 on 2021-01-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captain', models.TextField()),
                ('name', models.TextField()),
                ('position', models.TextField()),
                ('valid_steps', models.TextField()),
                ('add_steps', models.TextField()),
                ('hints', models.TextField()),
            ],
        ),
    ]
